### ISSUE TITLE
Problem with Bitwarden Feature

### ISSUE THREAD

**Issue by rudysuarez1** [generative-ai-inc/war-machine#30]
ERROR   🛑 Failed to retrieve bitwarden environment variables: Bad CPU type in executable (os error 86)
darwin x86_64 for mac OS

**Comment by jorge-menjivar** [comment]
This is an issue caused by a broken bitwarden SDK binary file from the bitwarden repo: https://github.com/bitwarden/sdk/issues/1046

I will switch to using aarch64 and x86_64 binaries directly, which will solve the issue, but will also save resources.
